baseURL: 'http://www.subond.com/'
languageCode: "zh-CN"
theme: "maupassant"
title: "凯文的个人博客"
author:
  name: "Kevin"

hasCJKLanguage: true
summaryLength: 30

# Category & Tag
default_category: uncategorized
category_map:
"NextMe": nextme
"杂谈": essay
"生活": life
"TECH": tech
"READ": read
"Go高性能编程": gohigh
tag_map:

# Directory
tag_dir: tags
archive_dir: archives
category_dir: categories

# 配置代码高亮
markup:
  highlight:
    lineNos: true
    style: "github"

params:
  author: "Kevin"
  subtitle: "专注于云计算网络，个人成长"
  keywords: "golang,博客"
  description: "专注于云网络，个人成长"
  busuanzi: true #启用不算子网页统计
  googleAd: ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch: true # 启用本地搜索
  cc:
    name: "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  links:
  - title: "github"
    name: "Github"
    url: "http://github.com/yusubond"
  - title: "微博"
    name: "微博"
    url: "https://weibo.cn/u/2746421033"

frontmatter:
  lastmod: [":fileModTime", "lastmod"]

# menu
menu:
  main:
  - identifier: "archives"
    name: "归档"
    url: /archives/
    weight: 2
  - identifier: "reading"
    name: "阅读"
    url: /reading/
    weight: 3
  - identifier: "about"
    name: "关于我"
    url: /about/
    weight: 4
