baseURL: 'http://www.subond.com/'
languageCode: "zh-CN"
theme: "maupassant"
title: "subond\'s blog"
author:
  name: "subond"

summaryLength: 140

# Category & Tag
default_category: uncategorized
category_map:
"NextMe": nextme
"杂谈": essay
"LIFE": life
"TECH": tech
"READ": read
tag_map:

# Directory
tag_dir: tags
archive_dir: archives
category_dir: categories

# 配置代码高亮
markup:
  highlight:
    lineNos: true
    style: "github"

params:
  cc:
    name: "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  links:
  - title: "github"
    name: "yusubond"
    url: "http://github.com/yusubond"

# menu
menu:
  main:
  - identifier: "archives"
    name: "归档"
    url: /archives/
    weight: 2
  - identifier: "reading"
    name: "阅读"
    url: /reading/
    weight: 3
  - identifier: "about"
    name: "关于"
    url: /about/
    weight: 4
